#!name=阿里云盘签到
#!desc=
[Script]

签到=type=cron,cronexp="5,10 0 * * *",wake-system=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js

#获取cookie=type=http-response,pattern=https:\/\/auth.aliyundrive.com\/v2\/account\/token,requires-body=1,script-path=https://raw.githubusercontent.com/lowking/Scripts/master/ali/aliYunPanCheckIn.js

[MITM] 
hostname= %APPEND% auth.aliyundrive.com
