#!name=Auto TF
#!desc=
[Script]

#TF信息获取 = Auto join TF = type=cron, cronexp=*/5 * * * *, timeout=30, script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Auto_Join_TF.js

Auto join TF = type=cron,cronexp=*/1 * * * * *,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Auto_Join_TF.js

[MITM]

hostname = %APPEND% testflight.apple.com
