#!name=Auto TF
#!desc=
[Script]

# TF信息获取
#TF信息获取 = type=http-request,pattern=^https:\/\/testflight\.apple\.com\/v3\/accounts/.*\/apps$,requires-body=0,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/TF_keys.js

# 自动加入 TestFlight 程序
Auto join TF = type=cron,cronexp=*/6 * * * *,timeout=120,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Auto_Join_TF.js

[MITM]
hostname = %APPEND% testflight.apple.com
