#!name=Auto TF
#!desc=
[Script]

#TF信息获取 = type=http-request,pattern=^https:\/\/testflight\.apple\.com\/v3\/accounts/.*\/apps$,requires-body=0,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/TF_keys.js

Auto join TF = type=cron,cronexp=*/1 * * * * *,script-path=https://raw.githubusercontent.com/chengkongyiban/shadowrocket/main/scripts/Auto_Join_TF.js

[MITM]

hostname = %APPEND% testflight.apple.com
